title: tbconroy
email: tbconroy@gmail.com
author: Tom Conroy
description: A blog by Tom Conroy on programming and technology.
baseurl: ""
url: "http://tbconroy.com"
twitter_username: tbconroy
github_username:  tbconroy

# Build settings
markdown: kramdown
theme: jekyll-whiteglass
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

jekyll-archives:
  enabled:
    - categories
  layout: category_archives
  permalinks:
    category: /categories/:name/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
